# Generated by Django 5.2.1 on 2025-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_payment_method_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)')], default='USD', max_length=3),
        ),
    ]
