# Generated by Django 5.2.1 on 2025-05-31 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('preferred_currency', models.CharField(choices=[('USD', 'United States Dollar ($)'), ('PKR', 'Pakistani Rupee (₨)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('SAR', 'Saudi Riyal (﷼)'), ('AED', 'UAE Dirham (د.إ)')], default='USD', max_length=3)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
